git:
  diffRenderers:
    - colorArg: always
      command: >
        delta
        --detect-dark-light=always
        --paging=never
        --line-numbers
        --hyperlinks
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

  # If true, do not allow force pushes
  disableForcePushing: true

# Auto-fill commit message form with the output of `generate-commit-message`
customCommands:
  - key: "<c-y>"
    context: "files"
    description: "Commit with generated message"
    loadingText: "Generating commit message..."
    prompts:
      - type: "input"
        title: "Commit message"
        key: "Msg"
        initialValue: '{{ runCommand "generate-commit-message" }}'
        # suggestions:
        #   command: "generate-commit-message"
    command: "git commit -m {{.Form.Msg | quote}}"
