git:
  pagers:
    - colorArg: always
      pager: >
        delta
        --dark
        --paging=never
        --line-numbers
        --hyperlinks
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

  # If true, do not allow force pushes
  disableForcePushing: true

# NOTE: This is experimental! Not really present in my workflow!
# Auto-fill commit message form with the output of `generate-commit-message`
customCommands:
  - key: "<c-y>"
    context: "files"
    description: "Commit with generated message"
    prompts:
      - type: "input"
        title: "Commit message"
        key: "Msg"
        initialValue: '{{ runCommand "generate-commit-message" }}'
        # suggestions:
        #   command: "generate-commit-message"
    command: 'git commit -m "{{.Form.Msg}}"'
